jobs:
 include:
  - stage: luacheck
    language: generic
    sudo: false
    addons:
     apt:
      packages:
       - luarocks
    before_install:
     - luarocks install --local luacheck
    script:
     - $HOME/.luarocks/bin/luacheck --no-color .

  - stage: unit test
    language: generic
    sudo: false
    addons:
     apt:
      packages:
       - luarocks
    script:
     - lua test.lua


  - stage: integration test
    language: generic
    services:
     - docker
    script:
     - ./integration-test.sh
