
services:
  mtt:
    image: ghcr.io/buckaroobanzay/mtt:latest
    volumes:
     - "./:/github/workspace"
    environment:
     INPUT_MODNAME: "epic"
     INPUT_TEST_MODE: "mod"
     INPUT_MAPGEN: "singlenode"
     INPUT_GIT_GAME_REPO: "https://git.0x7be.net/dirk/void"
